services:
  postgres:
    image: postgres:latest
    container_name: calendar_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: calendar-api-server
    build: ./server
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  client:
    container_name: calendar-admin-panel
    build: ./admin-panel
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data: